name: PR Check Ballerina Provider - DEVELOPMENT

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master
jobs:
  provider_pr_ci_dev:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Ballerina Environment
      - name: Set Up Ballerina
        uses: ballerina-platform/setup-ballerina@v1.1.0
        with:
          version: latest

      - name: Install dependencies
        run: bal build
        env:
          JAVA_HOME: /usr/lib/jvm/default-jvm

      - name: Run Ballerina Provider Service
        run: bal run &

      - name: Install Pact Verifier & Run
        run: |
          # Install the Pact Verfier
          curl -LO https://github.com/pact-foundation/pact-ruby-standalone/releases/download/v2.0.10/pact-2.0.10-linux-x86_64.tar.gz
          tar xzf pact-2.0.10-linux-x86_64.tar.gz
          ls
          pwd
          cd pact/bin
          ./pact-provider-verifier \
            --provider-base-url=$PACT_PROVIDER_BASE_URL \
            --pact-broker-base-url=$PACT_BROKER_URL \
            --broker-username=$PACT_BROKER_USERNAME \
            --broker-password=$PACT_BROKER_PASSWORD \
            --provider-version-branch=$PACT_PROVIDER_VERSION_BRANCH \
            --provider=$PACT_PROVIDER \
            --provider-app-version=$PACT_PROVIDER_APP_VERSION \
            --publish-verification-results \
            --tag-with-git-branch=true 
          cd ..
        env:
          PACT_CONSUMER: "BallerinaClient"
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_PROVIDER_BASE_URL: "http://localhost:9090"
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}
          PACT_PROVIDER_VERSION_BRANCH: "master"
          PACT_PROVIDER: BallerinaProvider
          PACT_PROVIDER_APP_VERSION: 0.1.0

      - name: Can I deploy to development environment
        run: |
          cd pact/bin \
          ./pact-broker can-i-deploy \
            -a=BallerinaProvider \
            -b=$PACT_BROKER_URL \
            --branch=master \
            --broker-username=$PACT_BROKER_USERNAME \
            --broker-password=$PACT_BROKER_PASSWORD \
            --to-environment=dev
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}

      - name: Deploy to Dev
        run: |
            echo "deployed"
      
      - name: Update pact broker
        run: |
          cd pact/bin
          ./pact-broker record-deployment \
            --environment=dev \
            -a=BallerinaProvider \
            --version=0.1.0 \ 
            --broker-username=$PACT_BROKER_USERNAME \
            --broker-password=$PACT_BROKER_PASSWORD \
            -b=$PACT_BROKER_URL
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_USERNAME: ${{ secrets.PACT_BROKER_USERNAME }}
          PACT_BROKER_PASSWORD: ${{ secrets.PACT_BROKER_PASSWORD }}



